#
# Copyright (C) 2017-2024 Tactical Computing Laboratories, LLC
# All Rights Reserved
# contact@tactcomplabs.com
#
# See LICENSE in the top level directory for licensing details
#

ifeq (, $(shell which sst-config))
 $(error "No sst-config in $(PATH), add `sst-config` to your PATH")
endif

CXX=$(shell sst-config --CXX)
CXXFLAGS=$(shell sst-config --ELEMENT_CXXFLAGS)
LDFLAGS=$(shell sst-config --ELEMENT_LDFLAGS)

SST_ELEMENTS_HOME?=$(shell sst-config SST_ELEMENT_LIBRARY SST_ELEMENT_LIBRARY_HOME)

CPPFLAGS = -I./ -I../include
CPPFLAGS += -I$(SST_ELEMENTS_HOME)/include

ifdef DEBUG
OPTIMIZE_FLAGS += -O0 -g
else
OPTIMIZE_FLAGS += -O3
endif

ifdef DEBUG_MODE
OPTIMIZE_FLAGS += -DDEBUG -DDEBUG_MODE -D__SST_DEBUG_OUTPUT__
endif

# some sst elements header files are  not included in release
CPPFLAGS += -I./memHierarchy

SOURCES := $(wildcard *.cc)
HEADERS := $(wildcard *.h)
OBJS := $(patsubst %.cc,%.o,$(SOURCES))

COMPONENT_LIB=libPIM.so

all: $(COMPONENT_LIB)

$(COMPONENT_LIB): $(OBJS)
	$(CXX) $(OPTIMIZE_FLAGS) $(CXXFLAGS) $(CPPFLAGS) *.o $(LDFLAGS) -o $@
%.o:%.cc $(HEADERS)
	$(CXX) $(OPTIMIZE_FLAGS) $(CXXFLAGS) $(CPPFLAGS) -c $<


.PHONY: uninstall
uninstall:
	sst-register -u MemControllerKG
	sst-register -u PIMMemController
	sst-register -u PIMBackend

install: $(COMPONENT_LIB)
	sst-register MemControllerKG MemControllerKG_LIBDIR=$(CURDIR)
	sst-register PIMMemController PIMMemController_LIBDIR=$(CURDIR)
	sst-register PIMBackend PIMBackend_LIBDIR=$(CURDIR)
	sst-register -l

.PHONY: clean
clean:
	rm -Rf *.o $(COMPONENT_LIB)
